apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: webapp-updater
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: webapp
      images:
        - alias: backend
          imageName: docker.io/shashankcj/web_app
          manifestTargets:
            helm:
              name: image.backend.repository
              tag: image.backend.tag

        - alias: frontend
          imageName: docker.io/shashankcj/web_app
          manifestTargets:
            helm:
              name: image.frontend.repository
              tag: image.frontend.tag

        - alias: celery
          imageName: docker.io/shashankcj/web_app
          manifestTargets:
            helm:
              name: image.celery.repository
              tag: image.celery.tag

  commonUpdateSettings:
    pullSecret: pullsecret:argocd/regcred
    updateStrategy: newest-build

  writeBackConfig:
    method: git
    gitConfig:
      repository: https://github.com/Shashankcj/fullstact_project_gitops.git
      branch: main