apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      imagePullSecrets:
        - name: regcred   # ✅ ADD HERE

      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres 5432; do
                echo "Waiting for postgres..."
                sleep 2
              done

      containers:
      - name: celery-beat
        image: {{ .Values.image.backend }}
        imagePullPolicy: Always
        command: ["celery", "-A", "CentralServer", "beat", "-l", "info"]
        env:
          - name: POSTGRES_HOST
            value: "postgres"

          - name: POSTGRES_DB
            value: "genesis"

          - name: POSTGRES_USER
            value: "genesis"

          - name: POSTGRES_PASSWORD
            value: "genesis123"

          - name: POSTGRES_PORT
            value: "5432"

          - name: SECRET_KEY
            value: "{{ .Values.secret.SECRET_KEY | quote }}"

          - name: REDIS_HOST
            value: "{{ .Values.env.REDIS_HOST }}"

          - name: REDIS_PORT
            value: "{{ .Values.env.REDIS_PORT }}"

          - name: REDIS_DB
            value: "{{ .Values.env.REDIS_DB }}"
      