apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-scaler
spec:
  scaleTargetRef:
    name: celery

  minReplicaCount: 1
  maxReplicaCount: 10

  triggers:
  - type: redis
    metadata:
      address: redis-service:6379
      listName: celery
      listLength: "5"