---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: webapp
spec:
  encryptedData:
    .dockerconfigjson: AgAicDfnsZvnxG9byyJ0CruoQyGLONShFdE4SL5A/3jRO7jU9kaZvKO6OLVS122w+nW0WmIBpTa0yRt/AhkDQQERGn7jLczC3E670Hi9c7+Fuag6F+xY7sNrGUCuEob5KPo7NzkgR9zbvCiKfzkb6zaAsVJzdMY93nwUDe3opehfGYcIBAzgTYgnNR5V4jU0iaX+//GVgDG+hxbCOyWTzm4r7hYU3gVZYB7GxJE14vRnXZYmwyaI5ap68liT4HGi+kLHUo9Jz5D0MXJ0J5vS+Us5pypkUZHert59QYR0tn1B5EOgj499Ff+a4ej/xFYwJC5jJoUNOvvUEZ5TLAhoD8R39c716csXne/U8Nmd3SuzFm67X/L2atW4AZCS6Eyq8pKS/Ovq4eESTWU4d+/OqOvbbr3dFRlPymt0fs5znY5a/yEJPw4uw2VWdCqIdoLj1aeHs7JhRPB+iESfSkl76PLEdb/rW9HVupih01T17lSQc37NSg16LP/gkgEgkZC+2tYXE5OvVKPEhEfp4S9qeU82fCpilxquylOor3b+ypsJJaLosTIDPQRVrjRCVjUlqAIAYKfJCyhXcahHItZgVyJfAXybRCp7HB8fgnwXw0D7X/kOxjqIHNvs6qPjL0MHJUEcmgDAkXgl76f0FZmt9A3XyNxH7tquzIlWVQGJOQUTTUNhZ9xcdDNigYBpapF+r+4ZL2a+R7TCGUA5ePahnMBuWh1dxMPuSe9VZSiX2wWui9Cj+HIm2BDo3pO3JumRaNR/h4Cj+6Bi8R5BEYgVxBeIa1IZNAzoybDtqPqb194Kh6W9Gv/dX4teFdvSPeknHEU7czusWuOOYsffL8k9uVosh7DAkyL+II7UaV48lqgG+R5wAjKlO9X8Qcvtfj7Llon5yyQ0wPkZ3HDfhnH2cHn0aZb39a+1FU6b9txZj3qaRNG/E//TOZtPfO7TGZIBcZEoUQ+KFBRUEdbi4BCB94I6G/eiYtnxqAZSZB1UHzny
  template:
    metadata:
      name: regcred
      namespace: webapp
    type: kubernetes.io/dockerconfigjson
